Close HTTP connection after we're done with it
With Python 3.4.1 (from Fedora 21), empty string is returned from
response.read() after the connection is closed causing this:

  Traceback (most recent call last):
    File "./laspyt.py", line 209, in <module>
      createSession()
    File "./laspyt.py", line 172, in createSession
      data = ElementTree.fromstring(response.read())
    File "/usr/lib64/python3.4/xml/etree/ElementTree.py", line 1326, in XML
      return parser.close()
  xml.etree.ElementTree.ParseError: no element found: line 1, column 0